FROM public.ecr.aws/lambda/python:3.13 AS zlib-base

# if installing zlib-ng from source, will be done for
# RUN PYTHON_ZLIB_NG_LINK_DYNAMIC=true pip install zlib-ng --no-binary zlib-ng

# if installing generic package from pip repository
# with unoptimized zlib-ng native library
# RUN pip install zlib-ng
RUN pip install aws-lambda-powertools

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.lambda_handler" ]

FROM zlib-base as zlib-ng

RUN dnf install -y tar gzip

COPY image_content/al2023-zlib-ng.tar.gz /tmp/
COPY image_content/etc/yum.repos.d/ /etc/yum.repos.d/

RUN cd /tmp && tar -xf ./al2023-zlib-ng.tar.gz && \
    mkdir -p /opt/al2023/next-gen/repos/zlib-ng && \
    cp -R /tmp/opt/al2023/next-gen/repos/zlib-ng/* /opt/al2023/next-gen/repos/zlib-ng/ && \
    rm -rf /tmp/*.tar.gz

RUN dnf repolist && dnf install -y zlib-ng-compat zlib-ng && dnf clean all
