FROM public.ecr.aws/lambda/java:21 AS zlib-base

ARG JAVA_PROJECT_ROOT=java/s3-files-parser

# Copy function code and runtime dependencies from Maven layout
COPY $JAVA_PROJECT_ROOT/target/classes ${LAMBDA_TASK_ROOT}
COPY $JAVA_PROJECT_ROOT/target/dependency/* ${LAMBDA_TASK_ROOT}/lib/
COPY $JAVA_PROJECT_ROOT/target/dependency/* ${LAMBDA_TASK_ROOT}

COPY $JAVA_PROJECT_ROOT/target/S3FileHandler.jar ${LAMBDA_TASK_ROOT}
#RUN mkdir -p /opt/lib

#COPY $JAVA_PROJECT_ROOT/target/dependency/* /opt/lib/
    
# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "cloud.plasticity.S3FileHandler::handleRequest" ]

FROM zlib-base AS zlib-ng

RUN dnf install -y tar gzip

COPY image_content/al2023-zlib-ng.tar.gz /tmp/
COPY image_content/etc/yum.repos.d/ /etc/yum.repos.d/

RUN cd /tmp && tar -xf ./al2023-zlib-ng.tar.gz && \
    mkdir -p /opt/al2023/next-gen/repos/zlib-ng && \
    cp -R /tmp/opt/al2023/next-gen/repos/zlib-ng/* /opt/al2023/next-gen/repos/zlib-ng/ && \
    rm -rf /tmp/*.tar.gz

RUN dnf repolist && dnf install -y zlib-ng-compat zlib-ng && dnf clean all

